#!/bin/bash 

SETTINGS_DIR="$( cd "$( dirname "$0" )" && pwd )"

if [ -e ~/.vim ] 
then
  mv ~/.vim ~/.vim.bk
fi

if [ -e ~/.vimrc ] 
then
  mv ~/.vimrc ~/.vimrc.bk
fi

ln -s $SETTINGS_DIR/.vim ~/.vim
ln -s $SETTINGS_DIR/.vimrc ~/.vimrc
ln -s $SETTINGS_DIR/.gvimrc ~/.gvimrc

git submodule init
git submodule update

vim +BundleInstall
